//
// This file contains an 'Intel Peripheral Driver' and is
// licensed for Intel CPUs and chipsets under the terms of your
// license agreement with Intel or your vendor.  This file may
// be modified by the user, subject to additional terms of the
// license agreement
//
/** @file
  PCH SMM Child Dispatcher Protocol.

  This protocol provides a parent dispatch service for a collection of
  chipset-specific SMI source.

  Copyright (c) 2009 - 2011, Intel Corporation. All rights reserved.<BR>
  This software and associated documentation (if any) is furnished
  under a license and may only be used or copied in accordance
  with the terms of the license. Except as permitted by such
  license, no part of this software or documentation may be
  reproduced, stored in a retrieval system, or transmitted in any
  form or by any means without the express written consent of
  Intel Corporation.

**/


#ifndef __SMM_UNCORE_DISPATCH2_H__
#define __SMM_UNCORE_DISPATCH2_H__

//
// Share some common definitions with Framework SMM
//
//#include <Protocol/SmmUncoreDispatch.h>

#include <PiSmm.h>


typedef struct _EFI_SMM_UNCORE_DISPATCH2_PROTOCOL EFI_SMM_UNCORE_DISPATCH2_PROTOCOL;

//
// Related Definitions
//
//
// Uncore Specific SMIs.  These are miscellaneous SMI sources that are supported by the
// Uncore specific SMI implementation.  These may change over time.  TrapNumber is only
// valid if the Type is Trap.
//
typedef enum {
  //
  // NOTE: NEVER delete items from this list/enumeration!  Doing so will prevent other versions
  // of the code from compiling.  If the ICH version your driver is written for doesn't support
  // some of these SMIs, then simply return EFI_UNSUPPORTED when a child/client tries to register
  // for them.
  //
  UncoreMch,
  UncorePme,
  UncoreRtcAlarm,
  UncoreRingIndicate,
  UncoreAc97Wake,
  UncoreSerialIrq,
  UncoreY2KRollover,
  UncoreTcoTimeout,
  UncoreOsTco,
  UncoreNmi,
  UncoreIntruderDetect,
  UncoreBiosWp,
  UncoreMcSmi,
  UncorePmeB0,
  UncoreThrmSts,
  UncoreSmBus,
  UncoreIntelUsb2,
  UncoreMonSmi7,
  UncoreMonSmi6,
  UncoreMonSmi5,
  UncoreMonSmi4,
  UncoreDevTrap13,
  UncoreDevTrap12,
  UncoreDevTrap11,
  UncoreDevTrap10,
  UncoreDevTrap9,
  UncoreDevTrap8,
  UncoreDevTrap7,
  UncoreDevTrap6,
  UncoreDevTrap5,
  UncoreDevTrap3,
  UncoreDevTrap2,
  UncoreDevTrap1,
  UncoreDevTrap0,
  UncoreIoTrap3,
  UncoreIoTrap2,
  UncoreIoTrap1,
  UncoreIoTrap0,
  UncorePciExpress,
  UncoreMonitor,
  UncoreSpi,
  UncoreQRT,
  UncoreGpioUnlock,
  //
  // INSERT NEW ITEMS JUST BEFORE THIS LINE
  //
  NUM_UNCORE_TYPES  // the number of items in this enumeration
} EFI_SMM_UNCORE_SMI_TYPE;


typedef struct {
  EFI_SMM_UNCORE_SMI_TYPE Type;
} EFI_SMM_UNCORE_REGISTER_CONTEXT;

//
// Member functions
//
/**
  Register a child SMI source dispatch function with a parent SMM driver

  @param  This                  Protocol instance pointer.
  @param  DispatchFunction      Pointer to dispatch function to be invoked for
                                this SMI source
  @param  RegisterContext       Pointer to the dispatch function's context.
                                The caller fills this context in before calling
                                the register function to indicate to the register
                                function the Uncore SMI source for which the dispatch
                                function should be invoked.
  @param  DispatchHandle        Handle generated by the dispatcher to track the
                                function instance.

  @retval EFI_SUCCESS           The dispatch function has been successfully
                                registered and the SMI source has been enabled.
  @retval EFI_DEVICE_ERROR      The driver was unable to enable the SMI source.
  @retval EFI_OUT_OF_RESOURCES  Not enough memory (system or SMM) to manage this
                                child.
  @retval EFI_INVALID_PARAMETER RegisterContext is invalid. The Uncore input value
                                is not within valid range.

**/
typedef
EFI_STATUS
(EFIAPI *EFI_SMM_UNCORE_DISPATCH2_REGISTER) (
  IN CONST EFI_SMM_UNCORE_DISPATCH2_PROTOCOL   *This,
  IN       EFI_SMM_HANDLER_ENTRY_POINT2      DispatchFunction,
  IN OUT   EFI_SMM_UNCORE_REGISTER_CONTEXT     *RegisterContext,
     OUT   EFI_HANDLE                        *DispatchHandle
  );

/**
  Unregister a child SMI source dispatch function with a parent SMM driver

  @param  This                  Protocol instance pointer.
  @param  DispatchHandle        Handle of dispatch function to deregister.

  @retval EFI_SUCCESS           The dispatch function has been successfully
                                unregistered and the SMI source has been disabled
                                if there are no other registered child dispatch
                                functions for this SMI source.
  @retval EFI_INVALID_PARAMETER Handle is invalid.
  @retval other                 TBD

**/
typedef
EFI_STATUS
(EFIAPI *EFI_SMM_UNCORE_DISPATCH2_UNREGISTER) (
  IN EFI_SMM_UNCORE_DISPATCH2_PROTOCOL          *This,
  IN EFI_HANDLE                               DispatchHandle
  );

//
// Interface structure for the SMM Ich n specific SMI Dispatch Protocol
//
/**
  @par Protocol Description:
  Provides a parent dispatch service for ICH SMI sources.

  @param Register
  Installs a child service to be dispatched by this protocol.

  @param UnRegister
  Removes a child service dispatched by this protocol.

**/
struct _EFI_SMM_UNCORE_DISPATCH2_PROTOCOL {
  EFI_SMM_UNCORE_DISPATCH2_REGISTER   Register;
  EFI_SMM_UNCORE_DISPATCH2_UNREGISTER UnRegister;
};

extern EFI_GUID gEfiSmmUncoreDispatch2ProtocolGuid;

#endif
