/** @file
  File name:    BUNITMEM.h
  Input File:   DNV_MRC.xlsx

  THIS FILE IS AUTO-GENERATED BY THE MSP TOOL. DO NOT CHANGE THIS CODE.

  If edits are needed in this file, they must be done via the MSP tool.

  If there is additional project-specific data required by the MSP, it
  can be placed in BUNITMEM.h, which is used for non-tool-generated
  data

  Includes register defines specific to a project.

  Copyright (c) 2005-2018 Intel Corporation. All rights reserved
  This software and associated documentation (if any) is furnished
  under a license and may only be used or copied in accordance
  with the terms of the license. Except as permitted by such
  license, no part of this software or documentation may be
  reproduced, stored in a retrieval system, or transmitted in any
  form or by any means without the express written consent of
  Intel Corporation.
**/
#ifndef _BUNITMEM_H_
#define _BUNITMEM_H_

#include "DataTypes.h"

#if USE_64_BIT_VARIABLES
#define UINTX UINT64
#else
#define UINTX UINT32
#endif

#define TOUUD_LO_BUNITMEM_REG                              0x000000A8
#ifndef ASM_INC
typedef union {
  struct {
    //
    // Register
    // 
    // Bits[31:0], RW, default = 0x80000
    //
    UINTX data : 32;
  } Bits;
  UINTX Data;
} TOUUD_LO_BUNITMEM_STRUCT;
#endif // ASM_INC

#define TOUUD_HI_BUNITMEM_REG                              0x000000AC
#ifndef ASM_INC
typedef union {
  struct {
    //
    // Register
    // 
    // Bits[31:0], RW, default = 0x1
    //
    UINTX data : 32;
  } Bits;
  UINTX Data;
} TOUUD_HI_BUNITMEM_STRUCT;
#endif // ASM_INC

#define TSEGMB_BUNITMEM_REG                                0x000000B8
#ifndef ASM_INC
typedef union {
  struct {
    //
    // Register
    // 
    // Bits[31:0], RW, default = 0x0
    //
    UINTX data : 32;
  } Bits;
  UINTX Data;
} TSEGMB_BUNITMEM_STRUCT;
#endif // ASM_INC

#define TOLUD_BUNITMEM_REG                                 0x000000BC
#ifndef ASM_INC
typedef union {
  struct {
    //
    // Register
    // 
    // Bits[31:0], RW, default = 0x40000
    //
    UINTX data : 32;
  } Bits;
  UINTX Data;
} TOLUD_BUNITMEM_STRUCT;
#endif // ASM_INC

#define BGSM_BUNITMEM_REG                                  0x000000B4
#ifndef ASM_INC
typedef union {
  struct {
    //
    // Register
    // 
    // Bits[31:0], RW, default = 0x0
    //
    UINTX data : 32;
  } Bits;
  UINTX Data;
} BGSM_BUNITMEM_STRUCT;
#endif // ASM_INC


#endif // _BUNITMEM_H_
